[mode]
mode = "release"

[log]
level = 5

[install]
reset = false
update = true

[database]
host = "192.168.100.2:3306"
user = "root"
password = "lwzw611116"
name = "cow"

[listen]
gateway = "0.0.0.0:30011"
backend= "0.0.0.0:30012"

[hall]
salt = "_8CTa8Qc7plKM7X9"
register_money = 100000
bind_money = 2000